TECHNIQUES_ROOT_DIR = "./Techniques"
MASTER_RECORD_FILE = TECHNIQUES_ROOT_DIR+"/MasterRecord.yml"
TACTICS_MAP_FILE = TECHNIQUES_ROOT_DIR+"/TacticsMap.yml"
TECHNIQUES_MAP_FILE = TECHNIQUES_ROOT_DIR+"/TechniquesMap.yml"

AUTOMATOR_DIR = "./automator"
AUTOMATOR_PLAYBOOKS_DIR = AUTOMATOR_DIR+"/Playbooks"
AUTOMATOR_OUTPUT_DIR = AUTOMATOR_DIR+"/Outputs"
AUTOMATOR_SCHEDULES_DIR = AUTOMATOR_DIR+"/Schedules.yml"

APP_LOCAL_DIR = "./local"
APP_LOG_FILE = APP_LOCAL_DIR+"/App_Log.csv"
TRACE_LOG_FILE = APP_LOCAL_DIR+"/Trace_Log.csv"
MSFT_TOKENS_FILE = APP_LOCAL_DIR+"/MSFT_Graph_Tokens.yml"